### ISSUE TITLE
Using PyAthena in Jupyterlab. Query results are saved in s3 but get an exception in PyAthena post that

### ISSUE THREAD

**Issue by vramku5** [laughingman7743/PyAthena#137]
I have set the following in the environment
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export AWS_DEFAULT_REGION=
export AWS_ATHENA_S3_STAGING_DIR=
export AWS_ATHENA_WORK_GROUP=

I connect in jupyterlab notebook using
%sql awsathena+rest://:@athena.us-east-1.amazonaws.com:443/<name of database>

I then execute a query as 
%sql  select ....

The query executes successfully in Athena and stores the results in the specified s3 bucket/folder.

However the results are not retrieved from there and shown in the notebook. I get an exception on the client saying the QueryExcecutionId is not able to be retrieved. Uploading the error stack that comes as an attachment

[pyathena-jupyterlab-error.log](https://github.com/laughingman7743/PyAthena/files/4539848/pyathena-jupyterlab-error.log)

**Comment by laughingman7743** [comment]
```
Failed to execute query.
Traceback (most recent call last):
  File "/Users/ramkumar/bin/anaconda3/lib/python3.7/site-packages/pyathena/common.py", line 206, in _execute
    **request).get('QueryExecutionId', None)
  File "/Users/ramkumar/bin/anaconda3/lib/python3.7/site-packages/pyathena/util.py", line 214, in retry_api_call
    return retry(func, *args, **kwargs)
  File "/Users/ramkumar/bin/anaconda3/lib/python3.7/site-packages/tenacity/__init__.py", line 391, in call
    do = self.iter(retry_state=retry_state)
  File "/Users/ramkumar/bin/anaconda3/lib/python3.7/site-packages/tenacity/__init__.py", line 338, in iter
    return fut.result()
  File "/Users/ramkumar/bin/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/Users/ramkumar/bin/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/ramkumar/bin/anaconda3/lib/python3.7/site-packages/tenacity/__init__.py", line 394, in call
    result = fn(*args, **kwargs)
  File "/Users/ramkumar/bin/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/ramkumar/bin/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: Queries of this type are not supported
---------------------------------------------------------------------------
InvalidRequestException                   Traceback (most recent call last)
~/bin/anaconda3/lib/python3.7/site-packages/pyathena/common.py in _execute(self, operation, parameters, work_group, s3_staging_dir, cache_size)
    205                                           logger=_logger,
--> 206                                           **request).get('QueryExecutionId', None)
    207             except Exception as e:

~/bin/anaconda3/lib/python3.7/site-packages/pyathena/util.py in retry_api_call(func, config, logger, *args, **kwargs)
    213     )
--> 214     return retry(func, *args, **kwargs)

~/bin/anaconda3/lib/python3.7/site-packages/tenacity/__init__.py in call(self, fn, *args, **kwargs)
    390         while True:
--> 391             do = self.iter(retry_state=retry_state)
    392             if isinstance(do, DoAttempt):

~/bin/anaconda3/lib/python3.7/site-packages/tenacity/__init__.py in iter(self, retry_state)
    337         if not (is_explicit_retry or self.retry(retry_state=retry_state)):
--> 338             return fut.result()
    339

~/bin/anaconda3/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    427             elif self._state == FINISHED:
--> 428                 return self.__get_result()
    429

~/bin/anaconda3/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    383         if self._exception:
--> 384             raise self._exception
    385         else:

~/bin/anaconda3/lib/python3.7/site-packages/tenacity/__init__.py in call(self, fn, *args, **kwargs)
    393                 try:
--> 394                     result = fn(*args, **kwargs)
    395                 except BaseException:

~/bin/anaconda3/lib/python3.7/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    315             # The "self" in this scope is referring to the BaseClient.
--> 316             return self._make_api_call(operation_name, kwargs)
    317

~/bin/anaconda3/lib/python3.7/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    625             error_class = self.exceptions.from_code(error_code)
--> 626             raise error_class(parsed_response, operation_name)
    627         else:

InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: Queries of this type are not supported

The above exception was the direct cause of the following exception:

DatabaseError                             Traceback (most recent call last)
~/bin/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1245                     self.dialect.do_execute(
-> 1246                         cursor, statement, parameters, context
   1247                     )

~/bin/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    587     def do_execute(self, cursor, statement, parameters, context=None):
--> 588         cursor.execute(statement, parameters)
    589

~/bin/anaconda3/lib/python3.7/site-packages/pyathena/util.py in _wrapper(*args, **kwargs)
    184         with _lock:
--> 185             return wrapped(*args, **kwargs)
    186     return _wrapper

~/bin/anaconda3/lib/python3.7/site-packages/pyathena/cursor.py in execute(self, operation, parameters, work_group, s3_staging_dir, cache_size)
     49                                        s3_staging_dir=s3_staging_dir,
---> 50                                        cache_size=cache_size)
     51         query_execution = self._poll(self._query_id)

~/bin/anaconda3/lib/python3.7/site-packages/pyathena/common.py in _execute(self, operation, parameters, work_group, s3_staging_dir, cache_size)
    208                 _logger.exception('Failed to execute query.')
--> 209                 raise_from(DatabaseError(*e.args), e)
    210         return query_id

~/bin/anaconda3/lib/python3.7/site-packages/future/utils/__init__.py in raise_from(exc, cause)
    402         execstr = "raise __python_future_raise_from_exc from __python_future_raise_from_cause"
--> 403         exec(execstr, myglobals, mylocals)
    404

~/bin/anaconda3/lib/python3.7/site-packages/pyathena/common.py in <module>

DatabaseError: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: Queries of this type are not supported

The above exception was the direct cause of the following exception:

DatabaseError                             Traceback (most recent call last)
<ipython-input-3-e34f28243e1e> in <module>
----> 1 get_ipython().run_line_magic('sql', '@warehousedb select date,date_format(from_unixtime(cast("timestamp" as bigint)/1000),\'%k\'),count(*) from impressionlog where date=date\'2019-05-03\' and date<=date\'2019-05-20\' and campaignid=133709 group by date,date_format(from_unixtime(cast("timestamp" as bigint)/1000),\'%k\') order by date,date_format(from_unixtime(cast("timestamp" as bigint)/1000),\'%k\')')
      2

~/bin/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2315                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2316             with self.builtin_trap:
-> 2317                 result = fn(*args, **kwargs)
   2318             return result
   2319

</Users/ramkumar/bin/anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-127> in execute(self, line, cell, local_ns)

~/bin/anaconda3/lib/python3.7/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188
    189         if callable(arg):

</Users/ramkumar/bin/anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-126> in execute(self, line, cell, local_ns)

~/bin/anaconda3/lib/python3.7/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188
    189         if callable(arg):

~/bin/anaconda3/lib/python3.7/site-packages/sql/magic.py in execute(self, line, cell, local_ns)
     93
     94         try:
---> 95             result = sql.run.run(conn, parsed['sql'], self, user_ns)
     96
     97             if result is not None and not isinstance(result, str) and self.column_local_vars:

~/bin/anaconda3/lib/python3.7/site-packages/sql/run.py in run(conn, sql, config, user_namespace)
    339                 txt = sqlalchemy.sql.text(statement)
    340                 result = conn.session.execute(txt, user_namespace)
--> 341             _commit(conn=conn, config=config)
    342             if result and config.feedback:
    343                 print(interpret_rowcount(result.rowcount))

~/bin/anaconda3/lib/python3.7/site-packages/sql/run.py in _commit(conn, config)
    318     if _should_commit:
    319         try:
--> 320             conn.session.execute('commit')
    321         except sqlalchemy.exc.OperationalError:
    322             pass  # not all engines can commit

~/bin/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py in execute(self, object_, *multiparams, **params)
    974         """
    975         if isinstance(object_, util.string_types[0]):
--> 976             return self._execute_text(object_, multiparams, params)
    977         try:
    978             meth = object_._execute_on_connection

~/bin/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py in _execute_text(self, statement, multiparams, params)
   1147             parameters,
   1148             statement,
-> 1149             parameters,
   1150         )
   1151         if self._has_events or self.engine._has_events:

~/bin/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1248         except BaseException as e:
   1249             self._handle_dbapi_exception(
-> 1250                 e, statement, parameters, cursor, context
   1251             )
   1252

~/bin/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   1474                 util.raise_from_cause(newraise, exc_info)
   1475             elif should_wrap:
-> 1476                 util.raise_from_cause(sqlalchemy_exception, exc_info)
   1477             else:
   1478                 util.reraise(*exc_info)

~/bin/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py in raise_from_cause(exception, exc_info)
    396     exc_type, exc_value, exc_tb = exc_info
    397     cause = exc_value if exc_value is not exception else None
--> 398     reraise(type(exception), exception, tb=exc_tb, cause=cause)
    399
    400

~/bin/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py in reraise(tp, value, tb, cause)
    150             value.__cause__ = cause
    151         if value.__traceback__ is not tb:
--> 152             raise value.with_traceback(tb)
    153         raise value
    154

~/bin/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1244                 if not evt_handled:
   1245                     self.dialect.do_execute(
-> 1246                         cursor, statement, parameters, context
   1247                     )
   1248         except BaseException as e:

~/bin/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    586
    587     def do_execute(self, cursor, statement, parameters, context=None):
--> 588         cursor.execute(statement, parameters)
    589
    590     def do_execute_no_params(self, cursor, statement, context=None):

~/bin/anaconda3/lib/python3.7/site-packages/pyathena/util.py in _wrapper(*args, **kwargs)
    183     def _wrapper(*args, **kwargs):
    184         with _lock:
--> 185             return wrapped(*args, **kwargs)
    186     return _wrapper
    187

~/bin/anaconda3/lib/python3.7/site-packages/pyathena/cursor.py in execute(self, operation, parameters, work_group, s3_staging_dir, cache_size)
     48                                        work_group=work_group,
     49                                        s3_staging_dir=s3_staging_dir,
---> 50                                        cache_size=cache_size)
     51         query_execution = self._poll(self._query_id)
     52         if query_execution.state == AthenaQueryExecution.STATE_SUCCEEDED:

~/bin/anaconda3/lib/python3.7/site-packages/pyathena/common.py in _execute(self, operation, parameters, work_group, s3_staging_dir, cache_size)
    207             except Exception as e:
    208                 _logger.exception('Failed to execute query.')
--> 209                 raise_from(DatabaseError(*e.args), e)
    210         return query_id
    211

~/bin/anaconda3/lib/python3.7/site-packages/future/utils/__init__.py in raise_from(exc, cause)
    401         myglobals['__python_future_raise_from_cause'] = cause
    402         execstr = "raise __python_future_raise_from_exc from __python_future_raise_from_cause"
--> 403         exec(execstr, myglobals, mylocals)
    404
    405     def raise_(tp, value=None, tb=None):

~/bin/anaconda3/lib/python3.7/site-packages/pyathena/common.py in <module>

DatabaseError: (pyathena.error.DatabaseError) An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: Queries of this type are not supported
[SQL: commit]
(Background on this error at: http://sqlalche.me/e/4xp6)
```

**Comment by laughingman7743** [comment]
```
DatabaseError: (pyathena.error.DatabaseError) An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: Queries of this type are not supported
```
I would like more information on table definitions, SELECT statements, Python code, etc.

**Comment by vramku5** [comment]
Thanks for the reply. I am pasting the query from the above log file. It is a fairly simple query.

get_ipython().run_line_magic('sql', '@warehousedb select date,date_format(from_unixtime(cast("timestamp" as bigint)/1000),\'%k\'),count(*) from impressionlog where date=date\'2019-05-03\' and date<=date\'2019-05-20\' and campaignid=133709 group by date,date_format(from_unixtime(cast("timestamp" as bigint)/1000),\'%k\') order by date,date_format(from_unixtime(cast("timestamp" as bigint)/1000),\'%k\')')

Please note that I not writing python code to perform the query. 

I am using the Jupyter sql interpreter 
%sql select .... 

and using the above select statement

Although it says "queries of this type is not supported", the query itself finishes successfully and the results is stored as a csv in s3. 

I think there is something missing with Athena not returning the query execution id, and the Jupiter python code trying to retrieve the query execution id and then hitting this error.

I tried the same example with PyAthenaJDBC also, and I get a similar error there as well. There also the query finishes successfully on Athena, and the results gets stored in s3 location.

**Comment by vramku5** [comment]
I tried a simpler query now

%sql @warehousedb select timestamp from impressionlog limit 1;

where timestamp is just the epoch time in the tale impressionlog

I am getting the exact same error as for the previous query. In this case also, the query is completed successfully on Athena, and query results stored in the right s3 location.

Only it is not getting retrieved and shown in the Jupterlab ui.

**Comment by laughingman7743** [comment]
I understand that when you run a query in JupyterLab you get an error. I will try it too.

**Comment by vramku5** [comment]
I turned the debug logs on and found that the last statement that is failing is a commit. Maybe Athena is returning an error when commit sent for a select. 

I set 
`%config SqlMagic.autocommit = False`

after this it is working fine.

**Comment by laughingman7743** [comment]
I see, would it be better to add some settings about JupyterLab to the README? 🤔

**Comment by vramku5** [comment]
Sure that would be good.
