### ISSUE TITLE
unable to import CSV containing dates or STRING (TEXT error)

### ISSUE THREAD

**Issue by thibault-ketterer** [laughingman7743/PyAthena#146]
While trying to create a table using PyAthena via SqlAlchemy I ran in the following Issue

`ParseException line 3:10 cannot recognize input near 'TEXT' ',' 'a_date' in column type`

My source data is
```
id,a_string,a_date
454096,hello,2020-06-06
```

- pandas==1.0.1 (also tested with 1.0.5)
- PyAthena==1.10.7
- python 3.7.3

It appears that calling `DataFrame.to_sql` isn’t able to infer the correct data type for string and date types when creating the target table in Athena.

Please see below a reproducible test case:

```python
aws_access_key_id = 'xxxxxx'
aws_secret_access_key = 'xxxxxxxxxxxxxxxx'
s3_staging_dir = 's3://aws-athena-query-results-YOUAWSID-eu-west-1/'

import io
import pandas as pd
from urllib.parse import quote_plus
from sqlalchemy import create_engine

region_name = 'eu-west-1'
schema_name = 'default'
s3_staging_dir = s3_staging_dir
s3_dir = s3_staging_dir + '/test_tk_pyathena/'
aws_access_key_id = aws_access_key_id
aws_secret_access_key = aws_secret_access_key

conn_str = f'awsathena+rest://{aws_access_key_id}:{aws_secret_access_key}@athena.{region_name}.amazonaws.com/'\
           f'{schema_name}?s3_staging_dir={s3_staging_dir}&s3_dir={s3_dir}&compression=snappy'

engine = create_engine(conn_str)

csv_file = io.StringIO("id,a_string,a_date\n"
                       "454096,hello,2020-06-06")

df = pd.read_csv(csv_file, parse_dates=['a_date'])
df.to_sql(name='thib_ketterer', con=engine, index=False, if_exists='replace')
```

Full stacktrace below:

$ python test_pyathena3_small.py 
```
Traceback (most recent call last):
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/pyathena/util.py", line 306, in _wrapper
    return wrapped(*args, **kwargs)
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/pyathena/cursor.py", line 79, in execute
    raise OperationalError(query_execution.state_change_reason)
pyathena.error.OperationalError: FAILED: ParseException line 3:10 cannot recognize input near 'TEXT' ',' 'a_date' in column type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_pyathena3_small.py", line 31, in <module>
    df.to_sql(name='thib_ketterer', con=engine, index=False, if_exists='replace')
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/pandas/core/generic.py", line 2663, in to_sql
    method=method,
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/pandas/io/sql.py", line 521, in to_sql
    method=method,
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/pandas/io/sql.py", line 1316, in to_sql
    table.create()
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/pandas/io/sql.py", line 649, in create
    self._execute_create()
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/pandas/io/sql.py", line 641, in _execute_create
    self.table.create()
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 926, in create
    bind._run_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2104, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1663, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 144, in traverse_single
    return meth(obj, **kw)
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 832, in visit_table
    include_foreign_key_constraints,  # noqa
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1082, in _execute_ddl
    compiled,
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/pyathena/util.py", line 306, in _wrapper
    return wrapped(*args, **kwargs)
  File "/Users/tketterer/.pyenv/versions/pandas/lib/python3.7/site-packages/pyathena/cursor.py", line 79, in execute
    raise OperationalError(query_execution.state_change_reason)
sqlalchemy.exc.OperationalError: (pyathena.error.OperationalError) FAILED: ParseException line 3:10 cannot recognize input near 'TEXT' ',' 'a_date' in column type
[SQL: 
CREATE EXTERNAL TABLE thib_ketterer (
	id BIGINT, 
	a_string TEXT, 
	a_date TEXT
)
STORED AS PARQUET
LOCATION 's3://aws-athena-query-results-YOURAWSID-eu-west-1//test_tk_pyathena/None/thib_ketterer/'
TBLPROPERTIES ('parquet.compress'='SNAPPY')


]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

I will be glad to help on this

**Comment by laughingman7743** [comment]
I need to implement TypeCompiler for the Athena data types.
I am trying the implementation in the following branches.
https://github.com/laughingman7743/PyAthena/pull/147

**Comment by thibault-ketterer** [comment]
you're awesome, thanks for the fix
