### ISSUE TITLE
reading NULL value for float data type column fails starting pyathena 1.11.1

### ISSUE THREAD

**Issue by bjcttam** [laughingman7743/PyAthena#169]
when using PandasCursor and loading the query results via cursor.as_pandas(), pyathena fails with the following error message:

Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1141, in pandas._libs.parsers.TextReader._convert_tokens
TypeError: Cannot cast array from dtype('O') to dtype('float64') according to the rule 'safe'

additional error message is

  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 941, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1073, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1147, in pandas._libs.parsers.TextReader._convert_tokens
ValueError: could not convert string to float:

To re-create this problem, 2 parquet file were read where 1 doesn't contain NULL while the other file did.

The problem is present with 1.11.1 & 1.11.2 while it is not present in 1.11.0 or earlier versions.

**Comment by laughingman7743** [comment]
The error seems to occur if the float value contains NULL. The following code easily reproduces it.
```
from pyathena import connect
from pyathena.pandas_cursor import PandasCursor

cursor = connect(s3_staging_dir="s3://BUCKET/path/to/",
                 region_name="us-west-2").cursor(PandasCursor)
result = cursor.execute("select * from (values (1.0), (NULL))").fetchall()
print(result)
```

Some of the options of read_csv can be changed at runtime. You can avoid this error by changing the value of null_values as follows:
```
from pyathena import connect
from pyathena.pandas_cursor import PandasCursor

cursor = connect(s3_staging_dir="s3://BUCKET/path/to/",
                 region_name="us-west-2").cursor(PandasCursor)
result = cursor.execute("select * from (values (1.0), (NULL))",
                        na_values="").fetchall()
print(result)
```
