### ISSUE TITLE
Get ValueError when running query with % (modulo) via sqlalchemy

### ISSUE THREAD

**Issue by daha** [laughingman7743/PyAthena#186]
I get "ValueError: unsupported format character ' ' (0x20) at index 1376" when I run a query with %, modulo operator, via sqlalchemy. You can see a longer stacktrace in the end of this message.

The query includes code like this:
`SELECT 1 % 3600000 = 0`

I do get the error with:
pyathena==2.0.0 or PyAthena==1.11.2
SQLAlchemy==1.3.20
python version 3.8.6

But I did not get the error with:
PyAthena==1.10.7
SQLAlchemy==1.3.17
python version 3.7.7

Stack trace:
...
    result = connection.execute(sql)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/pyathena/util.py", line 37, in _wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyathena/cursor.py", line 86, in execute
    self.query_id = self._execute(
  File "/usr/local/lib/python3.8/site-packages/pyathena/common.py", line 247, in _execute
    query = self._formatter.format(operation, parameters)
  File "/usr/local/lib/python3.8/site-packages/pyathena/formatter.py", line 187, in format
    return (operation % kwargs).strip() if kwargs is not None else operation.strip()
ValueError: unsupported format character ' ' (0x20) at index 1376

**Comment by laughingman7743** [comment]
Would it be possible to share stack trace information with [echo=True](https://docs.sqlalchemy.org/en/13/core/engines.html#sqlalchemy.create_engine.params.echo), or to share the parameters and queries executed?

**Comment by daha** [comment]
I created a minimal example which I can share (I did run it with echo=True):

2020-12-07 18:35:05,912 INFO sqlalchemy.engine.base.Engine
CREATE TABLE temporary_etl_tables.dummy
SELECT
    1 % 3600000 = 0 as is_hour
2020-12-07 18:35:05,912 INFO log.py:110
CREATE TABLE temporary_etl_tables.dummy
SELECT
    1 % 3600000 = 0 as is_hour
2020-12-07 18:35:05,913 INFO sqlalchemy.engine.base.Engine {}
2020-12-07 18:35:05,913 INFO log.py:110 {}
2020-12-07 18:35:05,913 INFO log.py:110 ROLLBACK
2020-12-07 18:35:05,913 INFO sqlalchemy.engine.base.Engine ROLLBACK
Traceback (most recent call last):
[...]
    result = connection.execute(sql)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/pyathena/util.py", line 37, in _wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyathena/cursor.py", line 86, in execute
    self.query_id = self._execute(
  File "/usr/local/lib/python3.8/site-packages/pyathena/common.py", line 247, in _execute
    query = self._formatter.format(operation, parameters)
  File "/usr/local/lib/python3.8/site-packages/pyathena/formatter.py", line 187, in format
    return (operation % kwargs).strip() if kwargs is not None else operation.strip()
ValueError: unsupported format character ' ' (0x20) at index 62

**Comment by laughingman7743** [comment]
You are probably not using sqlalchemy.sql.text. If you're not using it, you'll probably need to escape the % character.
Check out the simple example below.
```
from urllib.parse import quote_plus
import sqlalchemy
from sqlalchemy.engine import create_engine

conn_str = "awsathena+rest://:@athena.{region_name}.amazonaws.com:443/" \
           "{schema_name}?s3_staging_dir={s3_staging_dir}"
engine = create_engine(conn_str.format(
    region_name="us-west-2",
    schema_name="default",
    s3_staging_dir=quote_plus("s3://BUCKET/tmp/")))
query = sqlalchemy.sql.text(
    """
    SELECT 1 % 3600000 = 0 as is_hour            
    """
)
result = engine.execute(query)
print(result.fetchall())


conn_str = "awsathena+rest://:@athena.{region_name}.amazonaws.com:443/" \
           "{schema_name}?s3_staging_dir={s3_staging_dir}"
engine = create_engine(conn_str.format(
    region_name="us-west-2",
    schema_name="default",
    s3_staging_dir=quote_plus("s3://BUCKET/tmp/")))
query = """
SELECT 1 %% 3600000 = 0 as is_hour
"""
result = engine.execute(query)
print(result.fetchall())


# ValueError: unsupported format character ' ' (0x20) at index 18
conn_str = "awsathena+rest://:@athena.{region_name}.amazonaws.com:443/" \
           "{schema_name}?s3_staging_dir={s3_staging_dir}"
engine = create_engine(conn_str.format(
    region_name="us-west-2",
    schema_name="default",
    s3_staging_dir=quote_plus("s3://BUCKET/tmp/")))
query = """
SELECT 1 % 3600000 = 0 as is_hour
"""
result = engine.execute(query)
print(result.fetchall())
```

**Comment by daha** [comment]
Thanks I will try using sqlalchemy.sql.text, that will probably solve my issue...

**Comment by daha** [comment]
sqlalchemy.sql.text worked for me. Closing this issue. No bug...
