### ISSUE TITLE
PandasCursor fails on double column with nulls

### ISSUE THREAD

**Issue by EdwardJRoss** [laughingman7743/PyAthena#204]
When I run:

```
import pyathena
from pyathena.pandas.cursor import PandasCursor
# v1 from pyathena.pandas_cursor import PandasCursor

con = pyathena.connect()

query = "select * from (values  (0.33), (NULL))"

print(con.cursor(PandasCursor).execute(query).fetchall())
```

I expect: `[(0.33,), (nan,)]`

I get:
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    print(con.cursor(PandasCursor).execute(query).fetchall())
  File "pyathena/util.py", line 306, in _wrapper
    return wrapped(*args, **kwargs)
  File "pyathena/pandas_cursor.py", line 78, in execute
    self._result_set = AthenaPandasResultSet(
  File "pyathena/result_set.py", line 446, in __init__
    self._df = self._as_pandas()
  File "pyathena/result_set.py", line 543, in _as_pandas
    df = pd.read_csv(
  File "pandas/io/parsers.py", line 605, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "pandas/io/parsers.py", line 463, in _read
    return parser.read(nrows)
  File "pandas/io/parsers.py", line 1052, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "pandas/io/parsers.py", line 2056, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 850, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 982, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1056, in pandas._libs.parsers.TextReader._convert_tokens
ValueError: could not convert string to float: ''
```

I've tested this error occurs on Pandas 1.2.0 and PyAthena 2.1.0 and PyAthena 1.11.3.

The issue also occurs on PyAthena 1.11.1, but I get the expected result on PyAthena 1.11.0, so it's likely something in that release

**Comment by EdwardJRoss** [comment]
This is because null values are represented in the Athena CSV as an empty string and so it tries to convert the string to a float resulting in the error.

A workaround is to explicitly pass in `na_values = ['']` so that Pandas reads the empty strings in the CSV as null:

So the last line of the example above becomes
```
print(con.cursor(PandasCursor).execute(query, na_values=['']).fetchall())
```

**Comment by EdwardJRoss** [comment]
A possible solution would be to change the default value of `na_values` in `PandasCursor.execute` to be `[""]` instead of `None`.

I'm not sure if there are any drawbacks to this? It would be empty strings in a varchar column will become NA in PandasCursor

**Comment by laughingman7743** [comment]
It is not a good idea to set an array as the default argument value.
https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments
You can set `[""]` for `None`, but it's a problem when you actually want to set `None`. Is there any good workaround?

**Comment by EdwardJRoss** [comment]
There's a couple of possible workarounds:

1. The default argument could be set as the immutable tuple `("",)`, and then cast to a list (if necessary) before passing on. This could allow widening the type signature to `Optional[Iterable[str]]`).
2. The [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) for `na_values` allows a single value, so you set the default as `""`. This would mean widening the type signature to at least `Optional[Union[str, List[str]]]` (this matches the [current signature in `data-science-types`](https://github.com/predictive-analytics-lab/data-science-types/blob/master/pandas-stubs/__init__.pyi), but according to the Pandas docs the function should work on a wider range of options)
3. Having some special value like "default" that is then converted to the list `[""]` in code

They all have their tradeoffs, but I personally prefer 1.

**Comment by laughingman7743** [comment]
Thank you for suggesting some workarounds, choice 1 looks good :)
I'll implement it this weekend.

**Comment by dblado** [comment]
I believe this is still an issue for AsyncPandasCursor:

query_id, future=con.cursor(AsyncPandasCursor).execute(query)
result_set = future.result()
print(result_set.fetchall())

```py
TypeError                                 Traceback (most recent call last)
pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._convert_tokens()

TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
ipykernel_40764/2270984066.py in <module>
     27 
     28 query_id, future=con.cursor(AsyncPandasCursor).execute(query)
---> 29 result_set = future.result()
     30 print(result_set.fetchall())
     31 

concurrent/futures/_base.py in result(self, timeout)
    433                 raise CancelledError()
    434             elif self._state == FINISHED:
--> 435                 return self.__get_result()
    436             else:
    437                 raise TimeoutError()

concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

concurrent/futures/thread.py in run(self)
     55 
     56         try:
---> 57             result = self.fn(*self.args, **self.kwargs)
     58         except BaseException as exc:
     59             self.future.set_exception(exc)

pyathena/pandas/async_cursor.py in _collect_result_set(self, query_id, keep_default_na, na_values, quoting, kwargs)
     91             na_values=na_values,
     92             quoting=quoting,
---> 93             **kwargs,
     94         )
     95 

pyathena/pandas/result_set.py in __init__(self, connection, converter, query_execution, arraysize, retry_config, keep_default_na, na_values, quoting, **kwargs)
     71             and self.output_location.endswith((".csv", ".txt"))
     72         ):
---> 73             self._df = self._as_pandas()
     74         else:
     75             import pandas as pd

pyathena/pandas/result_set.py in _as_pandas(self)
    190                     na_values=self._na_values,
    191                     quoting=self._quoting,
--> 192                     **self._kwargs,
    193                 )
    194                 df = self._trunc_date(df)

pandas/util/_decorators.py in wrapper(*args, **kwargs)
    309                     stacklevel=stacklevel,
    310                 )
--> 311             return func(*args, **kwargs)
    312 
    313         return wrapper

pandas/io/parsers/readers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
    584     kwds.update(kwds_defaults)
    585 
--> 586     return _read(filepath_or_buffer, kwds)
    587 
    588 

pandas/io/parsers/readers.py in _read(filepath_or_buffer, kwds)
    486 
    487     with parser:
--> 488         return parser.read(nrows)
    489 
    490 

pandas/io/parsers/readers.py in read(self, nrows)
   1045     def read(self, nrows=None):
   1046         nrows = validate_integer("nrows", nrows)
-> 1047         index, columns, col_dict = self._engine.read(nrows)
   1048 
   1049         if index is None:

pandas/io/parsers/c_parser_wrapper.py in read(self, nrows)
    222         try:
    223             if self.low_memory:
--> 224                 chunks = self._reader.read_low_memory(nrows)
    225                 # destructive to chunks
    226                 data = _concatenate_chunks(chunks)

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.read_low_memory()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._convert_column_data()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._convert_tokens()

ValueError: could not convert string to float: 
```

**Comment by laughingman7743** [comment]
@dblado If you don't mind, please register the new issue. I'm sure I will address it.
