### ISSUE TITLE
View detection support

### ISSUE THREAD

**Issue by aaronsteers** [laughingman7743/PyAthena#244]
When using PyAthena with SQLAlchemy, I noticed that `get_table_names()` after inspection returns all tables _and views_ while `get_view_names()` raises a `NotImplementedError`. Is this expected? This is not critical for my use case but I'm happy to send a PR if someone can point me in the right direction.

Thanks!

**Comment by laughingman7743** [comment]
Do you have any problems with get_view_names not being implemented? Could you please share your use case?

**Comment by aaronsteers** [comment]
Yes - I'm getting this error when using inspection, specifically. My stack trace is:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/aj/Library/Caches/pypoetry/virtualenvs/tap-athena-xSE6trSW-py3.8/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aj/Library/Caches/pypoetry/virtualenvs/tap-athena-xSE6trSW-py3.8/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/aj/Library/Caches/pypoetry/virtualenvs/tap-athena-xSE6trSW-py3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aj/Library/Caches/pypoetry/virtualenvs/tap-athena-xSE6trSW-py3.8/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/aj/Source/sdk/singer_sdk/tap_base.py", line 357, in cli
    tap = cls(  # type: ignore  # Ignore 'type not callable'
  File "/Users/aj/Source/sdk/singer_sdk/tap_base.py", line 63, in __init__
    self._input_catalog or self.catalog_dict
  File "/Users/aj/Source/tap-athena/tap_athena/tap.py", line 29, in catalog_dict
    return AthenaStream.run_discovery(self.config)
  File "/Users/aj/Source/sdk/singer_sdk/streams/database.py", line 177, in run_discovery
    raise ex
  File "/Users/aj/Source/sdk/singer_sdk/streams/database.py", line 175, in run_discovery
    view_names = inspected.get_view_names(schema=schema_name)
  File "/Users/aj/Library/Caches/pypoetry/virtualenvs/tap-athena-xSE6trSW-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 412, in get_view_names
    return self.dialect.get_view_names(
  File "/Users/aj/Library/Caches/pypoetry/virtualenvs/tap-athena-xSE6trSW-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/interfaces.py", line 331, in get_view_names
    raise NotImplementedError()
```


Which points to this as the default implementation in sqlalchemy's stock `interfaces.py` (lines 325-331):

```
    def get_view_names(self, connection, schema=None, **kw):
        """Return a list of all view names available in the database.

        :param schema: schema name to query, if not the default schema.
        """

        raise NotImplementedError()
```

Here's a code snippet of how I'm implementing inspection.

```py
    def run_discovery(cls, tap_config) -> Dict[str, List[dict]]:
        """Return a catalog dict from discovery."""
        engine = cls.get_sqlalchemy_engine(tap_config)
        result: dict = {"streams": []}
        inspected = sqlalchemy.inspect(engine)
        for schema_name in inspected.get_schema_names():
            table_names = inspected.get_table_names(schema=schema_name)
            try:
                view_names = inspected.get_view_names(schema=schema_name)
            except NotImplementedError as ex:
                raise ex # For purposes of getting the stack trace. Otherwise:
                # TODO: Handle `get_view_names()`` not implemented
                # self.logger.warning(
                #     "Provider does not support get_view_names(). "
                #     "Streams list may be incomplete or `is_view` may be unpopulated."
                # )
                view_names = []
```

**Comment by aaronsteers** [comment]
@laughingman7743 - This code above actually appears to retrieve both tables and views, but it appears to return all under "tables".

**Comment by laughingman7743** [comment]
I see. I'll check your use case.
Pull requests are welcome. However, you need to set up GithubActions in the forked repository. In addition, the unit tests require an AWS environment. You will need to prepare your own account. The AWS account used in this repository is my personal account and cannot be shared.
