### ISSUE TITLE
error with pd.read_sql and sqlalchemy connection

### ISSUE THREAD

**Issue by plazmakeks** [laughingman7743/PyAthena#278]
I'm setting up an sqlalchemy engine using this connection string

`conn_str = awsathena+rest://:@athena.{region_name}.amazonaws.com:443/{schema_name}?s3_staging_dir={s3_staging_dir}`

which creates an sqlalchemy engine using pyathena for the dialect thing. I just switched to sqlalchemy as `pandas` from 1.4.0 on in `read_sql` requires an sqlalchemy connectionable, before it accepted a pyathena connection as well. Now, when running `pd.read_sql(query, my_new_sqlalchemy_connection(conn_str))` I get somewhere from within pyathena:

```2022-02-10 17:16:45,968   ERROR pyathena.common: Failed to execute query.
Traceback (most recent call last):
  File "/home/henning/my-project/.venv/lib/python3.8/site-packages/pyathena/common.py", line 413, in _execute
    query_id = retry_api_call(
  File "/home/henning/my-project/.venv/lib/python3.8/site-packages/pyathena/util.py", line 84, in retry_api_call
    return retry(func, *args, **kwargs)
  File "/home/henning/my-project/.venv/lib/python3.8/site-packages/tenacity/__init__.py", line 423, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/henning/my-project/.venv/lib/python3.8/site-packages/tenacity/__init__.py", line 360, in iter
    return fut.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/henning/my-project/.venv/lib/python3.8/site-packages/tenacity/__init__.py", line 426, in __call__
    result = fn(*args, **kwargs)
  File "/home/henning/my-project/.venv/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/henning/my-project/.venv/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 23:44: mismatched input '2019'. Expecting: '%', '*', '+', '-', '.', '/', 'AND', 'AT', 'EXCEPT', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OFFSET', 'OR', 'ORDER', 'UNION', '[', '||', <EOF>
```

I debugged through pyathena and found when changing

`query = table_name` in `pyathena.sqlalchemy_athena.AthenaDialect.get_columns` it works as expected. It this a bug or am I setting up something wrongly? 

edit:

```
name         : pyathena
version      : 2.4.1
```

**Comment by laughingman7743** [comment]
```
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 23:44: mismatched input '2019'. Expecting: '%', '*', '+', '-', '.', '/', 'AND', 'AT', 'EXCEPT', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OFFSET', 'OR', 'ORDER', 'UNION', '[', '||', <EOF>
```
InvalidRequestException seems to have been thrown.
There seems to be a problem with the query you are running. If the query can be shared, sharing it may help.

**Comment by plazmakeks** [comment]
Can't share the exact query but I set up something smaller which recreates the behavior:

```
SELECT 
   property 
FROM 
   table 
WHERE 
   "end" >= timestamp '2019-05-29' AND 
   "end" < timestamp '2022-01-15' AND 
   company='company1' AND 
   country = 'country1'
```
so setting

```
query = "SELECT property FROM table WHERE \"end\" >= timestamp \'2019-05-29\' AND \"end\" < timestamp \'2022-01-15\' AND company=\'company1\' AND country = \'country1\'"
```
and running

`pd.real_sql(query, pyathena_connection)` works in pandas 1.3.5

whereas

`pd.real_sql(query, sqlalchemy_connection)` breaks in pandas 1.4.0 with the above exception

where `end` is a `timestamp` in athena

Hope you can recreate it. Please note me for any finding or if you need some more information.

**Comment by laughingman7743** [comment]
The read_sql implementation seems to check for the existence of the table and retrieve the metadata before executing the query. However, looking at the behavior, it seems to go looking for the query itself as the table name, not the table name.
In v2.4.1, the implementation was to check for the existence of tables by executing a query on the information schema, so the SELECT statement was specified in a section where the table name was expected to be specified, which caused errors such as incorrect query syntax.
https://github.com/pandas-dev/pandas/blob/v1.4.2/pandas/io/sql.py#L575-L599
Since read_sql seems to be an implementation of read_sql_query with metadata retrieval added, no error will occur if read_sql_query is used directly.

The following issue has also been raised previously; it would be better to use read_sql_query directly.
https://github.com/laughingman7743/PyAthena/issues/222

In v2.5.0 or later, metadata retrieval has been changed to via API, so you will probably see the following error log.
https://github.com/laughingman7743/PyAthena/pull/286
```
Failed to get table metadata.
Traceback (most recent call last):
  File "/Users/foobar/github/PyAthena/pyathena/common.py", line 146, in _get_table_metadata
    response = retry_api_call(
  File "/Users/foobar/github/PyAthena/pyathena/util.py", line 84, in retry_api_call
    return retry(func, *args, **kwargs)
  File "/Users/foobar/.virtualenvs/pyathena-DhQ5A1u5-py3.8/lib/python3.8/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/foobar/.virtualenvs/pyathena-DhQ5A1u5-py3.8/lib/python3.8/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/Users/foobar/.pyenv/versions/3.8.1/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/foobar/.pyenv/versions/3.8.1/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/foobar/.virtualenvs/pyathena-DhQ5A1u5-py3.8/lib/python3.8/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/Users/foobar/.virtualenvs/pyathena-DhQ5A1u5-py3.8/lib/python3.8/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/foobar/.virtualenvs/pyathena-DhQ5A1u5-py3.8/lib/python3.8/site-packages/botocore/client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.MetadataException: An error occurred (MetadataException) when calling the GetTableMetadata operation: Table select * from many_rows not found. (Service: AmazonDataCatalog; Status Code: 400; Error Code: EntityNotFoundException; Request ID: 28209e60-58fe-499e-a18c-0d2216dd1b7e; Proxy: null)
```
Although the error log will appear, the query will be executed and the DataFrame should be available.

**Comment by laughingman7743** [comment]
This issue is closed for now. Please reopen if you have any problems.

**Comment by laughingman7743** [comment]
Using the read_sql method directly is the best choice in terms of performance. If for some reason it is difficult to use it, you can modify the log output of the pyathena package as follows.
```
import logging
from logging import CRITICAL
logging.getLogger("pyathena").setLevel(CRITICAL)
```
