### ISSUE TITLE
Creating tables with SQLAlchemy models supported?

### ISSUE THREAD

**Issue by terrylimnsv** [laughingman7743/PyAthena#279]
The first issue I encountered:

sqlalchemy.exc.CompileError: You need to specify the storage location for the table using the `awsathena_location` dialect keyword argument

I was able to address this with something like:

Base.metadata.tables['my_table'].dialect_options['awsathena']['location'] = location

There is probably a better solution, but this is all I could come up with so far.

Once I fixed this, I encountered this:

sqlalchemy.exc.DatabaseError: (pyathena.error.DatabaseError) An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:8: mismatched input 'EXTERNAL'. Expecting: 'OR', 'SCHEMA', 'TABLE', 'VIEW'

I debugged this on the Athena console and determined the issue is the SQL generated has primary key constraints which are not supported by Athena. Removing the primary key constraint in SQLAlchemy gives:

sqlalchemy.exc.ArgumentError: Mapper mapped class Institution->institution could not assemble any primary key columns for mapped table 'my_table'

Am I in unsupported territory or am I doing something wrong?

**Comment by laughingman7743** [comment]
Without the executed code and the stack trace, I can't examine anything. Please share the code you executed and the stack trace that resulted in the error first.

**Comment by laughingman7743** [comment]
Here are the tests related to CREATE TABLE in SQLAlchemy.
https://github.com/laughingman7743/PyAthena/blob/master/tests/test_sqlalchemy_athena.py#L572-L715
Maybe it will help you in some way.

**Comment by terrylimnsv** [comment]
> Here are the tests related to CREATE TABLE in SQLAlchemy. https://github.com/laughingman7743/PyAthena/blob/master/tests/test_sqlalchemy_athena.py#L572-L715 Maybe it will help you in some way.

Thanks, this did help me figure out a better way to provide the location:

    __table_args__ = { 'awsathena_location': location }

**Comment by laughingman7743** [comment]
Thanks, I'll look into it over the weekend.

**Comment by terrylimnsv** [comment]
> Thanks, I'll look into it over the weekend.

Great, thanks. I did more poking around and it seems SQLAlchemy requires a primary key. So perhaps in this scenario pyathena would omit this constraint when passing to Athena, since Athena does not support it?

**Comment by laughingman7743** [comment]
https://docs.sqlalchemy.org/en/14/faq/ormconfiguration.html#how-do-i-map-a-table-that-has-no-primary-key
I don't know the detailed implementation of SQLAlchemy, but I don't generate DDLs that specify about the primary key when generating DDLs, though.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/sqlalchemy_athena.py#L201-L234

**Comment by terrylimnsv** [comment]
Thanks for the link regarding mapping a table that has no primary key. However, I don't think the solution applies here. It shows how to specify multiple columns to make up a primary key.

**Comment by laughingman7743** [comment]
Why are you specifying PrimaryKey when Athena doesn't support it in the first place? I don't understand.

> class MyTable(Base):
>     __tablename__ = "mytable"
>     __table_args__ = { 'awsathena_location': BUCKET + "mytable" }
>     
>     pk = Column('pk', Integer, primary_key=True)
>     name = Column('name', String)
>

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/sqlalchemy_athena.py#L226-L231
This is where the PrimaryKey constraint will be added. This process is probably not necessary in Athena.

**Comment by laughingman7743** [comment]
In the case of DDL, I get an error if the Integer type is not INT.

I removed table constraints and fixed the INT type handling in the following branches.
https://github.com/laughingman7743/PyAthena/pull/281
Please check it out.

**Comment by terrylimnsv** [comment]
> Why are you specifying PrimaryKey when Athena doesn't support it in the first place? I don't understand.
> 
> > class MyTable(Base):
> > **tablename** = "mytable"
> > **table_args** = { 'awsathena_location': BUCKET + "mytable" }
> > ```
> > pk = Column('pk', Integer, primary_key=True)
> > name = Column('name', String)
> > ```

Only because SQLAlchemy complains if there is no primary key defined.

**Comment by terrylimnsv** [comment]
> In the case of DDL, I get an error if the Integer type is not INT.
> 
> I removed table constraints and fixed the INT type handling in the following branches. #281 Please check it out.

We had created an ugly work-around in the meantime by walking the ORM class attributes and generating the CREATE_TABLE SQL. I will try your solution as soon as I can. Thanks!

**Comment by laughingman7743** [comment]
I've added a simple test case.
https://github.com/laughingman7743/PyAthena/pull/281/commits/3dbe73d8be0bba80655771846fcbca0c736986fe
I'm not sure of the use case for this feature. If there is a test case you need, please let me know.

**Comment by terrylimnsv** [comment]
> In the case of DDL, I get an error if the Integer type is not INT.
> 
> I removed table constraints and fixed the INT type handling in the following branches. #281 Please check it out.

Unfortunately, it didn't work 100%. It looks like the primary key part is working, but there is some issue with the VARCHAR type handling. Athena requires a size to be specified for VARCHAR:

Traceback (most recent call last):
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/pyathena/util.py", line 37, in _wrapper
    return wrapped(*args, **kwargs)
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/pyathena/cursor.py", line 108, in execute
    raise OperationalError(query_execution.state_change_reason)
pyathena.error.OperationalError: FAILED: ParseException line 2:0 mismatched input ')' expecting ( near 'VARCHAR' in primitive type specification

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyathena_test.py", line 35, in <module>
    Base.metadata.tables['mytable'].create(athena_engine)
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 950, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3117, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2113, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 898, in visit_table
    include_foreign_key_constraints,  # noqa
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1289, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 81, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1387, in _execute_ddl
    compiled,
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2027, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/pyathena/util.py", line 37, in _wrapper
    return wrapped(*args, **kwargs)
  File "/home/ec2-user/environment/pyathena_test/pr_virtenv/lib/python3.7/site-packages/pyathena/cursor.py", line 108, in execute
    raise OperationalError(query_execution.state_change_reason)
sqlalchemy.exc.OperationalError: (pyathena.error.OperationalError) FAILED: ParseException line 2:0 mismatched input ')' expecting ( near 'VARCHAR' in primitive type specification
[SQL: 
CREATE EXTERNAL TABLE mytable (
        pk INT, 
        name VARCHAR
)
STORED AS PARQUET
LOCATION 's3://terry-athena-bucket/mytable/'

**Comment by terrylimnsv** [comment]
Update: I think the issue is that the type mappings from SQLAlchemy to Athena probably were not necessary before if only queries were used. In our work-around we are mapping the SQLAlchemy to Athena for the types we are using so far (not complete):

INTEGER->integer
DATETIME->timestamp
FLOAT->double
VARCHAR->string
BOOLEAN->boolean
BIGINT->bigint

and then the more ugly part:

VARCHAR(40)->varchar(40)

Btw, if I change the test code from:

    name = Column('name', String)

to

    name = Column('name', String(40))

Then PR #281 works.

**Comment by laughingman7743** [comment]
I'm trying a change in another branch to make it a STRING type when the length is not specified in VARCHAR.
https://github.com/laughingman7743/PyAthena/pull/286

**Comment by terrylimnsv** [comment]
> DDL

Mapping VARCHAR with no length to string seems reasonable. It is what we are doing in our work-around.

**Comment by terrylimnsv** [comment]
I tried pr #286. It seems to be handling varchar->string, but my test is failing with the primary key issue:

Failed to execute query.
Traceback (most recent call last):
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/pyathena/common.py", line 417, in _execute
    **request
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/pyathena/util.py", line 84, in retry_api_call
    return retry(func, *args, **kwargs)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:8: mismatched input 'EXTERNAL'. Expecting: 'OR', 'SCHEMA', 'TABLE', 'VIEW'
Traceback (most recent call last):
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/pyathena/common.py", line 417, in _execute
    **request
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/pyathena/util.py", line 84, in retry_api_call
    return retry(func, *args, **kwargs)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:8: mismatched input 'EXTERNAL'. Expecting: 'OR', 'SCHEMA', 'TABLE', 'VIEW'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/pyathena/util.py", line 37, in _wrapper
    return wrapped(*args, **kwargs)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/pyathena/cursor.py", line 96, in execute
    cache_expiration_time=cache_expiration_time,
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/pyathena/common.py", line 421, in _execute
    raise DatabaseError(*e.args) from e
pyathena.error.DatabaseError: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:8: mismatched input 'EXTERNAL'. Expecting: 'OR', 'SCHEMA', 'TABLE', 'VIEW'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyathena_test.py", line 35, in <module>
    Base.metadata.tables['mytable'].create(athena_engine)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 950, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3117, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2113, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 898, in visit_table
    include_foreign_key_constraints,  # noqa
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1289, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 81, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1387, in _execute_ddl
    compiled,
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2027, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/pyathena/util.py", line 37, in _wrapper
    return wrapped(*args, **kwargs)
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/pyathena/cursor.py", line 96, in execute
    cache_expiration_time=cache_expiration_time,
  File "/home/ec2-user/environment/pyathena_test/pr286_virtenv/lib/python3.7/site-packages/pyathena/common.py", line 421, in _execute
    raise DatabaseError(*e.args) from e
sqlalchemy.exc.DatabaseError: (pyathena.error.DatabaseError) An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:8: mismatched input 'EXTERNAL'. Expecting: 'OR', 'SCHEMA', 'TABLE', 'VIEW'
[SQL: 
CREATE EXTERNAL TABLE mytable (
        pk INTEGER,
        name STRING,
        PRIMARY KEY (pk)
)
STORED AS PARQUET
LOCATION 's3://terry-athena-bucket/mytable/'


]
(Background on this error at: https://sqlalche.me/e/14/4xp6)

**Comment by terrylimnsv** [comment]
Sorry, my mistake, I didn't realized it was merged. My original small test now works using pr 281.

**Comment by laughingman7743** [comment]
Thanks for the confirmation, I'll merge the PR.
I will be releasing the next version 2.5.0 once I have addressed #284.

**Comment by terrylimnsv** [comment]
OK, great! The next step on my side is to try our full application with all our tables and data types.
