### ISSUE TITLE
Avoid raising exception if metadata retrieval is failing

### ISSUE THREAD

**Issue by plazmakeks** [laughingman7743/PyAthena#326]
Hi,

in reference to my previous issue [278](https://github.com/laughingman7743/PyAthena/issues/278) I would love to not have the exception on the failure on retrieving metadata. 

```Failed to get table metadata.
Traceback (most recent call last):
  File "/Users/foobar/github/PyAthena/pyathena/common.py", line 146, in _get_table_metadata
    response = retry_api_call(
  File "/Users/foobar/github/PyAthena/pyathena/util.py", line 84, in retry_api_call
    return retry(func, *args, **kwargs)
  File "/Users/foobar/.virtualenvs/pyathena-DhQ5A1u5-py3.8/lib/python3.8/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/foobar/.virtualenvs/pyathena-DhQ5A1u5-py3.8/lib/python3.8/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/Users/foobar/.pyenv/versions/3.8.1/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/foobar/.pyenv/versions/3.8.1/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/foobar/.virtualenvs/pyathena-DhQ5A1u5-py3.8/lib/python3.8/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/Users/foobar/.virtualenvs/pyathena-DhQ5A1u5-py3.8/lib/python3.8/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/foobar/.virtualenvs/pyathena-DhQ5A1u5-py3.8/lib/python3.8/site-packages/botocore/client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.MetadataException: An error occurred (MetadataException) when calling the GetTableMetadata operation: Table select * from many_rows not found. (Service: AmazonDataCatalog; Status Code: 400; Error Code: EntityNotFoundException; Request ID: 28209e60-58fe-499e-a18c-0d2216dd1b7e; Proxy: null)
```

The proposed solution in the linked issue is not really feasible in a productive solution and having all those exceptions in the logs isn't something one would want to have as well.

I would really appreciate if this could be fixed.

**Comment by laughingman7743** [comment]
I can't solve the problem because the error is actually occurring, the Pandas implementation is obviously bad, so either raise an issue with Pandas or do that as it is easy to limit the log output.
https://github.com/laughingman7743/PyAthena/issues/278#issuecomment-1131841524

**Comment by laughingman7743** [comment]
The following branch has been changed to not log output if it fails to retrieve metadata via SQLAlchemy.
Please check it out.
https://github.com/laughingman7743/PyAthena/pull/353
