### ISSUE TITLE
Unknown parameter in QueryExecutionContext: "Catalog", must be one of: Database

### ISSUE THREAD

**Issue by zachliu** [laughingman7743/PyAthena#336]
I'm using `pyathena==2.9.4` under Python 3.7.4

My test code is copied from README:

```python
from pyathena import connect
from pyathena.cursor import DictCursor

cursor = connect(s3_staging_dir="s3://YOUR_S3_BUCKET/path/to/",
                 region_name=REGION,
                 cursor_class=DictCursor).cursor()

cursor.execute("SELECT * FROM DATABASE.TABLE LIMIT 10;")
```

it returned an error i don't understand:

```
Failed to execute query.
Traceback (most recent call last):
  File "/home/zach/my-project/.venv/lib/python3.7/site-packages/pyathena/common.py", line 455, in _execute
    **request
  File "/home/zach/my-project/.venv/lib/python3.7/site-packages/pyathena/util.py", line 84, in retry_api_call
    return retry(func, *args, **kwargs)
  File "/home/zach/my-project/.venv/lib/python3.7/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/zach/my-project/.venv/lib/python3.7/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/home/zach/.asdf/installs/python/3.7.4/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/zach/.asdf/installs/python/3.7.4/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/zach/my-project/.venv/lib/python3.7/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/home/zach/my-project/.venv/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/zach/my-project/.venv/lib/python3.7/site-packages/botocore/client.py", line 634, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/zach/my-project/.venv/lib/python3.7/site-packages/botocore/client.py", line 682, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/zach/my-project/.venv/lib/python3.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in QueryExecutionContext: "Catalog", must be one of: Database
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    cursor.execute("SELECT * FROM <database>.<table> LIMIT 10")
  File "/home/zach/my-project/.venv/lib/python3.7/site-packages/pyathena/util.py", line 37, in _wrapper
    return wrapped(*args, **kwargs)
  File "/home/zach/my-project/.venv/lib/python3.7/site-packages/pyathena/cursor.py", line 97, in execute
    cache_expiration_time=cache_expiration_time,
  File "/home/zach/my-project/.venv/lib/python3.7/site-packages/pyathena/common.py", line 459, in _execute
    raise DatabaseError(*e.args) from e
pyathena.error.DatabaseError: Parameter validation failed:
Unknown parameter in QueryExecutionContext: "Catalog", must be one of: Database
```

**Comment by laughingman7743** [comment]
I have tried running the following code and it does not seem to generate any errors in my environment.
```
from pyathena import connect
from pyathena.cursor import DictCursor

cursor = connect(
    s3_staging_dir="s3://bucket/path/to/",
    region_name="us-west-2",
    cursor_class=DictCursor,
).cursor()
cursor.execute(
    """
    SELECT * FROM test.one_row
    """
)
print(cursor.fetchall())
```

**Comment by zachliu** [comment]
found the problem! although we have
```
boto3 = ">=1.4.4"
botocore = ">=1.5.52"
```
my 
```
boto3==1.9.253
botocore==1.12.253
```
are not compatible

i also tried 
```
boto3==1.4.4
botocore==1.5.95
```
they don't work either

so i guess we need to update the `pyproject.toml`. the 2 boto-related lines are 2 years old

**Comment by laughingman7743** [comment]
Thank you, I will update the boto3 and botocore dependencies.

**Comment by laughingman7743** [comment]
https://boto3.amazonaws.com/v1/documentation/api/1.13.20/reference/services/athena.html#Athena.Client.start_query_execution
https://github.com/boto/boto3/blob/develop/CHANGELOG.rst#11320
I checked the documentation and it seems that `catalog` has been supported since probably 1.13.20.

**Comment by zachliu** [comment]
yeah 1.13.19 doesn't have it
https://boto3.amazonaws.com/v1/documentation/api/1.13.19/reference/services/athena.html#Athena.Client.start_query_execution

since boto packages get updated almost on a daily basis, we can use higher version than 1.13.20 on the safe side :grin:
