### ISSUE TITLE
Connection not bound in to_sql method with Pandas 1.4

### ISSUE THREAD

**Issue by laughingman7743** [laughingman7743/PyAthena#351]
https://github.com/laughingman7743/PyAthena/pull/350

With Pandas 1.3.5, no error occurs.
https://github.com/laughingman7743/PyAthena/runs/7485630193?check_suite_focus=true

With Pandas 1.4.3, an error occurs.
https://github.com/laughingman7743/PyAthena/runs/7485630227?check_suite_focus=true
```
  =================================== FAILURES ===================================
  ______________ TestSQLAlchemyAthena.test_to_sql_parquet[engine0] _______________
  
  self = <tests.test_sqlalchemy_athena.TestSQLAlchemyAthena object at 0x7f8df355a5b0>
  engine = Engine(awsathena+rest://athena.***.amazonaws.com:443/pyathena_test_wi4gcu5j3q?compression=snappy&file_format=par...2Fpyathena%2Fgithub%2Fworkflows%2F&s3_staging_dir=***)
  
      @pytest.mark.parametrize(
          "engine",
          [{"file_format": "parquet", "compression": "snappy"}],
          indirect=["engine"],
      )
      def test_to_sql_parquet(self, engine):
          engine, conn = engine
          table_name = "to_sql_{0}".format(str(uuid.uuid4()).replace("-", ""))
          df = pd.DataFrame(
              {
                  "col_int": np.int32([1]),
                  "col_bigint": np.int64([12345]),
                  "col_float": np.float32([1.0]),
                  "col_double": np.float64([1.2345]),
                  "col_string": ["a"],
                  "col_boolean": np.bool_([True]),
                  "col_timestamp": [datetime(2020, 1, 1, 0, 0, 0)],
                  "col_date": [date(2020, 12, 31)],
              }
          )
          # Explicitly specify column order
          df = df[
              [
                  "col_int",
                  "col_bigint",
                  "col_float",
                  "col_double",
                  "col_string",
                  "col_boolean",
                  "col_timestamp",
                  "col_date",
              ]
          ]
  >       df.to_sql(
              table_name,
              engine,
              schema=ENV.schema,
              index=False,
              if_exists="replace",
              method="multi",
          )
  
  tests/test_sqlalchemy_athena.py:454: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  .tox/py38/lib/python3.8/site-packages/pandas/core/generic.py:2951: in to_sql
      return sql.to_sql(
  .tox/py38/lib/python3.8/site-packages/pandas/io/sql.py:697: in to_sql
      return pandas_sql.to_sql(
  .tox/py38/lib/python3.8/site-packages/pandas/io/sql.py:1729: in to_sql
      table = self.prep_table(
  .tox/py38/lib/python3.8/site-packages/pandas/io/sql.py:1628: in prep_table
      table.create()
  .tox/py38/lib/python3.8/site-packages/pandas/io/sql.py:842: in create
      self._execute_create()
  .tox/py38/lib/python3.8/site-packages/pandas/io/sql.py:828: in _execute_create
      self.table.create(bind=self.pd_sql.connectable)
  .tox/py38/lib/python3.8/site-packages/sqlalchemy/sql/schema.py:959: in create
      bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  .tox/py38/lib/python3.8/site-packages/sqlalchemy/engine/base.py:3147: in _run_ddl_visitor
      conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  .tox/py38/lib/python3.8/site-packages/sqlalchemy/engine/base.py:2130: in _run_ddl_visitor
      visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  .tox/py38/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py:524: in traverse_single
      return meth(obj, **kw)
  .tox/py38/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py:895: in visit_table
      self.connection.execute(
  .tox/py38/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1306: in execute
      return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  .tox/py38/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py:80: in _execute_on_connection
      return connection._execute_ddl(
  .tox/py38/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1395: in _execute_ddl
      compiled = ddl.compile(
  .tox/py38/lib/python3.8/site-packages/sqlalchemy/sql/elements.py:501: in compile
      return self._compiler(dialect, **kw)
  .tox/py38/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py:32: in _compiler
      return dialect.ddl_compiler(dialect, self, **kw)
  pyathena/sqlalchemy_athena.py:199: in __init__
      super(AthenaDDLCompiler, self).__init__(
  .tox/py38/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py:451: in __init__
      self.string = self.process(self.statement, **compile_kwargs)
  .tox/py38/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py:486: in process
      return obj._compiler_dispatch(self, **kwargs)
  .tox/py38/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py:82: in _compiler_dispatch
      return meth(self, **kw)
  pyathena/sqlalchemy_athena.py:500: in visit_create_table
      text.append(f"{self.post_create_table(table)}\n")
  pyathena/sqlalchemy_athena.py:510: in post_create_table
      self._get_table_location_specification(table, dialect_opts, raw_connection),
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  self = <pyathena.sqlalchemy_athena.AthenaDDLCompiler object at 0x7f8ddef3ebe0>
  table = Table('to_sql_d42e212e7dfb46f7aba09292d19c01e3', MetaData(), Column('col_int', Integer(), table=<to_sql_d42e212e7dfb46...01e3>), Column('col_date', Date(), table=<to_sql_d42e212e7dfb46f7aba09292d19c01e3>), schema='pyathena_test_wi4gcu5j3q')
  dialect_opts = <sqlalchemy.sql.base._DialectArgDict object at 0x7f8ddef3e5e0>
  raw_connection = None
  
      def _get_table_location_specification(self, table, dialect_opts, raw_connection):
          location = self._get_table_location(table, dialect_opts, raw_connection)
          text = []
          if location:
              text.append(f"LOCATION '{location}'")
          else:
              if raw_connection:
                  raise exc.CompileError(
                      "`location` or `s3_staging_dir` parameter is required "
                      "in the connection string"
                  )
              else:
  >               raise exc.CompileError(
                      "The location of the table should be specified "
                      "by the dialect keyword argument `awsathena_location`"
                  )
  E               sqlalchemy.exc.CompileError: The location of the table should be specified by the dialect keyword argument `awsathena_location`
  
  pyathena/sqlalchemy_athena.py:321: CompileError
  ------------------------------ Captured log call -------------------------------
  ERROR    pyathena.common:common.py:159 Failed to get table metadata.
  Traceback (most recent call last):
    File "/home/runner/work/PyAthena/PyAthena/pyathena/common.py", line 152, in _get_table_metadata
      response = retry_api_call(
    File "/home/runner/work/PyAthena/PyAthena/pyathena/util.py", line 84, in retry_api_call
      return retry(func, *args, **kwargs)
    File "/home/runner/work/PyAthena/PyAthena/.tox/py38/lib/python3.8/site-packages/tenacity/__init__.py", line 404, in __call__
      do = self.iter(retry_state=retry_state)
    File "/home/runner/work/PyAthena/PyAthena/.tox/py38/lib/python3.8/site-packages/tenacity/__init__.py", line 349, in iter
      return fut.result()
    File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/concurrent/futures/_base.py", line 437, in result
      return self.__get_result()
    File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
      raise self._exception
    File "/home/runner/work/PyAthena/PyAthena/.tox/py38/lib/python3.8/site-packages/tenacity/__init__.py", line 407, in __call__
      result = fn(*args, **kwargs)
    File "/home/runner/work/PyAthena/PyAthena/.tox/py38/lib/python3.8/site-packages/botocore/client.py", line 395, in _api_call
      return self._make_api_call(operation_name, kwargs)
    File "/home/runner/work/PyAthena/PyAthena/.tox/py38/lib/python3.8/site-packages/botocore/client.py", line 725, in _make_api_call
      raise error_class(parsed_response, operation_name)
  botocore.errorfactory.MetadataException: An error occurred (MetadataException) when calling the GetTableMetadata operation: Table to_sql_d42e212e7dfb46f7aba09292d19c01e3 not found. (Service: AmazonDataCatalog; Status Code: 400; Error Code: EntityNotFoundException; Request ID: 443275aa-6218-4f1d-b355-1ae1479edd4d; Proxy: null)
```

SQLAlchemy version is the same:
```
    - Installing sqlalchemy (1.4.39)
```

**Comment by laughingman7743** [comment]
https://github.com/pandas-dev/pandas/blob/v1.3.5/pandas/io/sql.py#L847-L853
```
    def _execute_create(self):
        # Inserting table into database, add to MetaData object
        if _gt14():
            self.table = self.table.to_metadata(self.pd_sql.meta)
        else:
            self.table = self.table.tometadata(self.pd_sql.meta)
        self.table.create()
```
https://github.com/pandas-dev/pandas/blob/v1.4.3/pandas/io/sql.py#L822-L828
```
    def _execute_create(self):
        # Inserting table into database, add to MetaData object
        if _gt14():
            self.table = self.table.to_metadata(self.pd_sql.meta)
        else:
            self.table = self.table.tometadata(self.pd_sql.meta)
        self.table.create(bind=self.pd_sql.connectable)
```
