### ISSUE TITLE
PyAthena 3.0.x doesn't work with SQLAlchemy 1.4.36

### ISSUE THREAD

**Issue by mdeshmu** [laughingman7743/PyAthena#445]
Hi,

Apache Superset uses [SQLAlchemy 1.4.36](https://github.com/apache/superset/blob/master/requirements/base.txt#L279) which when used with recently released PyAthena versions 3.0.x throws below error:

`NameError: name 'Union' is not defined`

Here is the error stack trace:
```
Traceback (most recent call last):
  File "/usr/local/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 567, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 407, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_migrate/cli.py", line 149, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/local/lib/python3.8/site-packages/flask_migrate/__init__.py", line 98, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_migrate/__init__.py", line 185, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/superset/extensions/../migrations/env.py", line 126, in <module>
    run_migrations_online()
  File "/app/superset/extensions/../migrations/env.py", line 118, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/migration.py", line 561, in run_migrations
    step.migration_fn(**kw)
  File "/app/superset/migrations/versions/2022-04-01_14-38_a9422eeaae74_new_dataset_models_take_2.py", line 900, in upgrade
    postprocess_columns(session)
  File "/app/superset/migrations/versions/2022-04-01_14-38_a9422eeaae74_new_dataset_models_take_2.py", line 811, in postprocess_columns
    quoted_expression = get_identifier_quoter(drivername)(
  File "/app/superset/connectors/sqla/utils.py", line 211, in get_identifier_quoter
    return SqlaURL.create(drivername).get_dialect()().identifier_preparer.quote
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 679, in get_dialect
    entrypoint = self._get_entrypoint()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 661, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 341, in load
    return impl.load()
  File "/usr/local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 209, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/pyathena/sqlalchemy/pandas.py", line 4, in <module>
    from pyathena.sqlalchemy.base import AthenaDialect
  File "/usr/local/lib/python3.8/site-packages/pyathena/sqlalchemy/base.py", line 861, in <module>
    class AthenaDialect(DefaultDialect):
  File "/usr/local/lib/python3.8/site-packages/pyathena/sqlalchemy/base.py", line 979, in AthenaDialect
    def _get_table(self, connection, table_name: str, schema: Optional[str] = None, **kw):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 198, in decorate
    decorated = _exec_code_in_env(code, env, fn.__name__)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 228, in _exec_code_in_env
    exec(code, env)
  File "<string>", line 1, in <module>
NameError: name 'Union' is not defined
```

**Comment by mdeshmu** [comment]
Locking down to PyAthena==2.25.2 fixes the issue. So something changed between two versions that causes this.

**Comment by laughingman7743** [comment]
Type hints have been added in classes related to SQLAlchemy since v3.0.0. The changes are as follows
https://github.com/laughingman7743/PyAthena/pull/420/

The part of the code that uses Union is below.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/sqlalchemy/base.py#L667
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/sqlalchemy/base.py#L883
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/sqlalchemy/base.py#L921

**Comment by laughingman7743** [comment]
Pull requests are welcome.😉

**Comment by mdeshmu** [comment]
I haven't gone through the code but I will take a look to decide what best fits here i.e. 1) wrapping type hints in quotes or 2) postpone evaluations by adding this at the top of each file 

from __future__ import annotations

then will raise a PR.

**Comment by mdeshmu** [comment]
thank you @xuganyu96 for fixing it. Looking forward to 3.0.3 :)

**Comment by laughingman7743** [comment]
I think you can check the master branch to see if this issue has been fixed, so please check.
https://pip.pypa.io/en/stable/cli/pip_install/#examples
https://python-poetry.org/docs/cli/#add

**Comment by mdeshmu** [comment]
Sure

**Comment by mdeshmu** [comment]
I have checked. I am not more getting Union error when using master branch

**Comment by laughingman7743** [comment]
Okey, I will release v3.0.3. Thanks.

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/releases/tag/v3.0.3
