### ISSUE TITLE
Handle InvalidRequestException errors raised

### ISSUE THREAD

**Issue by koshy1123** [laughingman7743/PyAthena#45]
I have a script using Athena + SQLAlchemy to run a query and have the results of that query read in as a pandas DataFrame. However, for some queries (which are long), I get this error:
```
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: Your query has exceeded the maximum query length of 262144 bytes. Please reduce the length of your query and try again.  If you continue to see this issue after reducing your query length,  contact customer support for further assistance.
```
But I can't do this
```
try:
   run_query()
except botocore.errorfactory.InvalidRequestException:
   run_query_differently()
```
because it says 
```
AttributeError: module 'botocore.errorfactory' has no attribute 'InvalidRequestException'
```
The way it's usually handled is to use `client.exceptions.InvalidRequestException` but that requires access to the same client that was used to run the query. 

Any ideas on how to to do this using the connections that PyAthena creates?

**Comment by koshy1123** [comment]
My bad - the actual error I get is a `sqlalchemy.exc.DatabaseError` and I can `except` that and my script runs fine, however in my run, I still continue to see this 
```
Failed to execute query.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pyathena/common.py", line 165, in _execute
    **request)
  File "/usr/local/lib/python3.6/site-packages/pyathena/util.py", line 44, in retry_api_call
    return retry(func, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 330, in call
    start_time=start_time)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 279, in iter
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 333, in call
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: Your query has exceeded the maximum query length of 262144 bytes. Please reduce the length of your query and try again.  If you continue to see this issue after reducing your query length,  contact customer support for further assistance.
```

**Comment by koshy1123** [comment]
Gotcha - I ended up implementing a version of this^, thanks! Only concerned that I was using a private variable `_connection` in my script, otherwise works!

Closing this issue.
